      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This tells GitHub to ignore everything else and only host what's inside build
          path: './frontend/build/'
